// HTML sanitization for mindmaplib React adapter.
//
// Every HTML string generated by generateHTML() passes through DOMPurify before
// DOM insertion. The sanitizer config strips all non-allowed tags, restricts
// href schemes, and enforces link safety attributes.

import DOMPurify from 'dompurify'

const ALLOWED_TAGS = [
  'p',
  'h1',
  'h2',
  'h3',
  'ul',
  'ol',
  'li',
  'pre',
  'code',
  'strong',
  'em',
  'a',
  'br',
]

const ALLOWED_ATTR = ['href', 'target', 'rel']

// DOMPurify hook: enforce link rules after sanitization attributes are processed.
// Registered once at module load.
let hookRegistered = false

function ensureHookRegistered(): void {
  if (hookRegistered) return
  DOMPurify.addHook('afterSanitizeAttributes', (node) => {
    if (node.tagName === 'A') {
      const href = node.getAttribute('href') || ''
      // Restrict href schemes to http, https, mailto
      if (!/^(https?:|mailto:)/i.test(href)) {
        node.removeAttribute('href')
      }
      // Only allow target=_blank
      const target = node.getAttribute('target')
      if (target && target !== '_blank') {
        node.setAttribute('target', '_blank')
      }
      // Enforce rel when target=_blank
      if (node.getAttribute('target') === '_blank') {
        node.setAttribute('rel', 'noopener noreferrer')
      }
    }
  })
  hookRegistered = true
}

/**
 * Sanitize HTML for safe DOM insertion.
 * Strips script tags, event handlers, javascript: and data: URLs.
 * Enforces link href scheme restrictions and rel attributes.
 */
export function sanitizeMindmapHtml(html: string): string {
  ensureHookRegistered()
  const cleaned = DOMPurify.sanitize(html, {
    ALLOWED_TAGS,
    ALLOWED_ATTR,
    FORBID_ATTR: ['style', 'class', 'id', 'onerror', 'onload', 'onclick'],
  })
  return cleaned
}
